config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from . import views
urlpatterns = [
    path('', include('food.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('home/', views.HomeView.as_view(), name='home'),
    
    
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views
from .views import PlacesListView, PlaceDetailView, AddCommentView, UpdateCommentView, DeleteCommentView
app_name = 'food'
urlpatterns = [
    path('', PlacesListView.as_view(), name='index'),
    path('category/<int:id>/', views.category, name='category'),
    path('detail/<int:id>/', PlaceDetailView.as_view(), name='detail'),
    path('<int:id>/comment', AddCommentView.as_view(), name='add_comment'),
    path('comment_update/', UpdateCommentView.as_view(), name='update_comment'),
    path('comment_delete/<int:id>/', DeleteCommentView.as_view(), name='delete_comment'),
]

food/models.py
from django.db import models
from django.utils import timezone
from users.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Category(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = 'Categories'


class Place(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    address = models.CharField(max_length=255)
    place_image = models.ImageField(upload_to='place_image/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='places')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

class Owner(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField()
    email = models.EmailField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

class PlaceOwner(models.Model):
    place = models.ForeignKey(Place, on_delete=models.CASCADE)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.place.name} by {self.owner.full_name}'

class PlaceComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name="reviews")
    comment = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.user.username} gave {self.stars_given} to {self.place.name}'

class Meal(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    place = models.ForeignKey(Place, on_delete=models.CASCADE, related_name='meals')
    image = models.ImageField(upload_to='meal_images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='meals')

    def __str__(self):
        return self.name

class UserFavoriteFood(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.ForeignKey(Meal, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} likes {self.food.name}'

food/forms.py
from django import forms
from .models import PlaceComment

class PlaceCommentForm(forms.ModelForm):
    stars_given = forms.IntegerField(max_value=5, min_value=1)
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows':8}))
                                                        
    
    class Meta:
        model = PlaceComment
        fields = ('comment', 'stars_given')

food/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.core.paginator import Paginator
from django.urls import reverse
from .models import Place, PlaceComment, Category, Meal
from django.views import View
from .forms import PlaceCommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

def category(request,id):
    categories = Category.objects.all()
    category = Category.objects.get(id=id)
    places = category.places.all()
    data = {
        'places': places,
        'category': category,
        'categories': categories    
    }
    
    return render(request,'food/index.html', context=data)


class PlacesListView(View):
    
    def get(self, request):
        places=Place.objects.all()
        categories = Category.objects.all()
        search_place = request.GET.get('q', '')
        
        if search_place:
            places = places.filter(name__contains=search_place)
            
        
        page_size = request.GET.get("page_size", 5)
        paginator = Paginator(places, page_size)
        page_num = request.GET.get("page", 1)
        page_object = paginator.get_page(page_num)
        
        return render(request, 'food/index.html', context={'places':page_object, "q": search_place, 'categories': categories})
    
def cat_meal(request,id):
    categories = Category.objects.all()
    category = Category.objects.get(id=id)
    places = category.places.all()
    data = {
        'places': places,
        'category': category,
        'categories': categories    
    }
    
    return render(request,'food/index.html', context=data)
    
class PlaceDetailView(DetailView):
    model = Place
    template_name = 'food/detail.html'
    context_object_name = 'food'
    pk_url_kwarg = 'id'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Получаем список блюд, относящихся к этому месту
        context['meals'] = Meal.objects.filter(place=self.object)
        # Передаем форму комментария
        context['form'] = PlaceCommentForm()
        return context



class AddCommentView(LoginRequiredMixin, View):
    def post(self, request, id):
        place = Place.objects.get(id=id)
        comment_form = PlaceCommentForm(data=request.POST)
        
        if comment_form.is_valid():
            PlaceComment.objects.create(
                place = place,
                user = request.user,
                comment = comment_form.cleaned_data['comment'],
                stars_given = comment_form.cleaned_data['stars_given'],
            )
            return redirect(reverse('food:detail', kwargs={'id': place.id}))
        
        return render(request, 'food/detail.html', {'form': comment_form, 'place': place})
    
    


class UpdateCommentView(LoginRequiredMixin, View):
    def put(self, request, id):
        try:
            comment = PlaceComment.objects.get(id=id, user=request.user)
            comment.comment = request.POST['comment']
            comment.stars_given = request.POST['stars_given']
            comment.save()
            return JsonResponse({'success': True})
        except PlaceComment.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Comment does not exist or you do not have permission to edit it'})


class DeleteCommentView(LoginRequiredMixin, View):
    def delete(self, request, id):
        try:
            comment = PlaceComment.objects.get(id=id, user=request.user)
            comment.delete()
            return JsonResponse({'success': True})
        except PlaceComment.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Comment does not exist or you do not have permission to delete it'})
        

food/templates/food/detail.html
{% extends 'base.html' %}


{% block content %}
<section class="breadcrumbs-custom">
    <div class="parallax-container" data-parallax-img="images/breadcrumbs-bg.jpg">
      <div class="breadcrumbs-custom-body parallax-content context-dark darken-overlay">
        <div class="container">
          <h2 class="breadcrumbs-custom-title">{{food.name}}</h2>
        </div>
      </div>
    </div>
    <div class="breadcrumbs-custom-footer">
      <div class="container">
        <ul class="breadcrumbs-custom-path">
          <li><a href="{% url 'food:index' %}">Asosiy</a></li>
          <li><a href="grid-shop.html">Do'kon</a></li>
          <li class="active">Joy</li>
        </ul>
      </div>
    </div>
  </section>
  <!-- Single Product-->
  <section class="section section-sm section-first bg-default">
    <div class="container">
      <div class="row row-30">
        <div class="col-lg-6">
          <div class="slick-vertical slick-product">
            <!-- Slick Carousel-->
            <div class="slick-slider carousel-parent" id="carousel-parent" data-items="1" data-swipe="true" data-child="#child-carousel" data-for="#child-carousel">
              <div class="item">
                <div class="slick-product-figure"><img src="{{food.place_image.url}}" alt="" width="530" height="480">
                </div>
              </div>
              
             
            </div>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="single-product">
            <h3 class="text-transform-none fw-medium">{{food.name}}</h3>
            <div class="group-md group-middle">
              <div class="single-product-price">{{food.address}}</div>
            </div>
            <p>{{food.description}}</p>
            <hr class="hr-gray-100">
           
            
            <hr class="hr-gray-100">
            
          </div>
        </div>
      </div>


      <div class="tabs-custom tabs-horizontal tabs-line" id="tabs-1">
        <!-- Nav tabs-->
        <div class="nav-tabs-wrap">
          <ul class="nav nav-tabs nav-tabs-1">
            <li class="nav-item" role="presentation"><a class="nav-link active" href="#tabs-1-1" data-bs-toggle="tab">Izohlar</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-1-2" data-bs-toggle="tab">Qo'shimcha ma'lumot</a></li>
            <li class="nav-item" role="presentation"><a class="nav-link" href="#tabs-1-3" data-bs-toggle="tab">Buyurtma and To'lov</a></li>
          </ul>
        </div>
        <!-- Tab panes-->
        <div class="tab-content tab-content-1">
          <div class="tab-pane fade show active" id="tabs-1-1">
            {% for review in food.reviews.all %}
            <div class="box-comment">
              <div class="unit flex-column flex-sm-row unit-spacing-md">
                <div class="unit-left"><a class="box-comment-figure"  href="#"><img src="{{ review.user.profile_image.url }}" alt="" width="100" height="100"></a></div>
                <div class="unit-body">
                  <div class="group-sm group-justify">
                    <div>
                      <div class="group-xs group-middle">
                        <h5 class="box-comment-author"><a href="#">{{ review.user.username }}</a></h5>
                        {% if review.stars_given == 1 %}
                            <div class="box-rating"><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 2 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 3 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 4 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 5 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% else %}
                        {% endif %}
                      </div>
                    </div>
                    <div class="box-comment-time">
                      <time datetime="2022-11-30">{{ review.created_at|date:"F d, Y" }}</time>
                    </div>
                  </div>
                  <p class="box-comment-text">{{review.comment}}</p>
                </div>
              </div>
            </div>
            {% endfor %}

            <h4 class="text-transform-none fw-medium">Izoh qoldirish</h4>

            <form class="rd-form " method="post" action="{% url 'food:add_comment' food.id %}">
                {% csrf_token %}
                <div class="row row-20 row-md-30">
                <div class="col-lg-8">
                  <div class="row row-20 row-md-30">
                    <div class="col-sm-6">
                      <div class="form-wrap">
                        <input class="form-input" id="contact-first-name-2" type="text" name="stars_given" >
                        <label class="form-label" for="contact-first-name-2">Baholang</label>
                      </div>
                    </div>
                    
                  </div>
                </div>

                <div class="col-lg-4">
                  <div class="form-wrap">
                    <label class="form-label" for="contact-message-2">Izoh qoldiring</label>
                    <textarea class="form-input textarea-lg" id="contact-message-2" name="comment" ></textarea>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </form>
          </div>

          <div class="tab-pane fade" id="tabs-1-2">
            <div class="single-product-info">
              <div class="unit unit-spacing-md flex-column flex-sm-row align-items-sm-center">
                <div class="unit-left"><span class="icon icon-80 mdi mdi-information-outline"></span></div>
                <div class="unit-body">
                  <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire.</p>
                </div>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="tabs-1-3">
            <div class="single-product-info">
              <div class="unit unit-spacing-md flex-column flex-sm-row align-items-sm-center">
                <div class="unit-left"><span class="icon icon-80 mdi mdi-truck-delivery"></span></div>
                <div class="unit-body">
                  <p>c auctor augue mauris augue neque gravida. Vitae sapien pellentesque habitant morbi tristique senectus et. Vitae auctor eu augue ut lectus. Congue eu consequat ac felis. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Ut venenatis tellus in metus. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Gravida dictum fusce ut placerat orci nulla pellentesque.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Related Products-->
  <section class="section section-sm section-last bg-default">
    <div class="container">
      <h4 class="fw-sbold">Menyu</h4>
      <div class="row row-lg row-30 row-lg-50 justify-content-center">
        {% for m in meals %}
        <div class="col-sm-6 col-md-5 col-lg-3">
          <!-- Product-->
          <article class="product">
            <div class="product-body">
              <div class="product-figure"><img src="{{m.image.url}}" alt="" width="220" height="160">
              </div>
              <h5 class="product-title"><a href="single-product.html">{{m.name}}</a></h5>
              <div class="product-price-wrap">
              
                <div class="product-price">{{m.price}} so'm</div>
              </div>
            </div>
            <div class="product-button-wrap">
              <div class="product-button"><button value="{{m.id}}" class="button button-secondary button-zakaria like-button" >❤</button></div>
              
            </div>
          </article>
        </div>
        {% endfor %}
        
        
      </div>
    </div>
  </section>

{% endblock %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('.like-button').click(function() {
            var mealId = $(this).val(); // Получаем идентификатор блюда
            $.ajax({
                type: 'POST',
                url: '/add_to_favorites/', // URL-адрес вашего представления для добавления в избранное
                data: {
                    'meal_id': mealId,
                    'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function(response) {
                    alert('Блюдо добавлено в избранное!');
                },
                error: function(xhr, status, error) {
                    alert('Произошла ошибка: ' + error);
                }
            });
        });
    });
</script>

food/templates/food/feed.html
{% extends 'base.html' %}
      <!-- Page Header-->
      {% block content %}
      <section class="breadcrumbs-custom">
        <div class="parallax-container" data-parallax-img="images/breadcrumbs-bg.jpg">
          <div class="breadcrumbs-custom-body parallax-content context-dark darken-overlay">
            <div class="container">
              <h2 class="breadcrumbs-custom-title">Izohlar</h2>
            </div>
          </div>
        </div>
        <div class="breadcrumbs-custom-footer">
          <div class="container">
            <ul class="breadcrumbs-custom-path">
              <li><a href="{% url 'food:index' %}">Asosiy</a></li>
              <li class="active">Izohlar</li>
            </ul>
          </div>
        </div>
      </section>
      <!-- Section Shop-->
      <section class="section section-xl bg-default text-md-start">
        <div class="container">
          <div class="row row-50 row-md-60">
            <div class="col-lg-8 col-xl-9 mx-auto">
              <div class="inset-xl-right-70">
                <div class="row row-50 row-md-60 row-lg-80 row-xl-100">
                {% for review in place_reviews %}
                  <div class="col-12">
                    <!-- Post Modern-->
                    <article class="post post-modern box-xxl">
                      <div class="post-modern-panel">
                        <div><a class="post-modern-tag" href="#">Izohlar</a></div>
                        <div>
                          <time class="post-modern-time" datetime="2022-08-09">{{ review.created_at|date:"F d, Y" }}</time>
                        </div>
                      </div>
                      <h3 class="post-modern-title">{{review.user.username}}</h3><img src="{{review.place.place_image.url}}" alt="" width="800" height="394">
                      <p class="post-modern-text">{{review.comment}}</p><a class="post-modern-link" href="blog-post.html"></a>
                      {% if review.stars_given == 1 %}
                            <div class="box-rating"><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 2 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 3 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 4 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% elif review.stars_given == 5 %}
                        <div class="box-rating"><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span><span class="icon mdi mdi-star"></span></div>
                        {% else %}
                        {% endif %}
                    </article>
                  </div>
                {% endfor %}

                  
                </div>
                <div class="pagination-wrap">
                  <!-- Bootstrap Pagination-->
                  <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if place_reviews.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">&laquo; First</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ place_reviews.previous_page_number }}">Oldingi</a>
                            </li>
                        {% endif %}
                        
                        {% for num in place_reviews.paginator.page_range %}
                            <li class="page-item {% if num == place_reviews.number %}active{% endif %}">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endfor %}
                        
                        {% if place_reviews.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ place_reviews.next_page_number }}">Keyingi</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ place_reviews.paginator.num_pages }}">Oxirgi &raquo;</a>
                            </li>
                        {% endif %}
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
            
{% endblock %}

food/templates/food/index.html
{% extends 'base.html' %}

{% block content %}

    

    <!-- About Us-->
    {% include 'details/about.html' %}


    
    <!-- Place -->
    {% include 'details/places.html' %}


    

{% endblock %}
  