config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from . import views
urlpatterns = [
    path('', include('food.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('home/', views.HomeView.as_view(), name='home'),
    
    
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views
from .views import PlacesListView, PlaceDetailView, AddCommentView, UpdateCommentView, DeleteCommentView
app_name = 'food'
urlpatterns = [
    path('', PlacesListView.as_view(), name='index'),
    path('category/<int:id>/', views.category, name='category'),
    path('detail/<int:id>/', PlaceDetailView.as_view(), name='detail'),
    path('<int:id>/comment', AddCommentView.as_view(), name='add_comment'),
    path('comment_update/', UpdateCommentView.as_view(), name='update_comment'),
    path('comment_delete/<int:id>/', DeleteCommentView.as_view(), name='delete_comment'),
]

users/urls.py
from django.urls import path
from . import views
from .views import LoginView, LogoutView, RegisterView, CustomPasswordChangeView
from django.contrib.auth import views as auth_views
app_name = 'users'


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileUpdateView.as_view(), name='profile'),
    path('profile_new/', views.ProfileView.as_view(), name='profile_new'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    path('api/login/', LoginView.as_view(), name='api-login'),
    path('api/logout/', LogoutView.as_view(), name='api-logout'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    profile_image = models.ImageField(upload_to='profile_images/', default='profile_images/default.jpg')
    
        

users/forms.py
from django import forms
from users.models import User
from django.contrib.auth.forms import PasswordChangeForm

class RegisterForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
        
        

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput) 

class PasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Old Password', strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'class': 'form-control'}))
    new_password1 = forms.CharField(label='New Password', strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}))
    new_password2 = forms.CharField(label='Confirm New Password', strip=False, widget=forms.PasswordInput(attrs={'autocomplete': 'new-password', 'class': 'form-control'}))

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get('new_password1')
        new_password2 = cleaned_data.get('new_password2')
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError('New passwords do not match.')
        return cleaned_data
    
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_image')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from .forms import RegisterForm, LoginForm, ProfileUpdateForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy





class RegisterView(View):
    def get(self, request):
        form = RegisterForm
        return render(request, 'users/register.html', context={'form': form})
    
    
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return redirect('user:login')
        
        return render(request, 'users/register.html', context={'form': form})
    
    
class LoginView(View):
    def get(self, request): 
        form = LoginForm()
        
        return render(request, 'users/login.html', context={'form': form})
    
    
    def post(self, request):
        form = LoginForm(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('food:index')
        
        return render(request, 'users/login.html', context={'form': form})  
    
    
class CustomPasswordChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'users/reset_password.html'
    success_url = reverse_lazy('food:index')

class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('users:login')


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        form = ProfileUpdateForm(instance=request.user)
        return render(request, 'users/profile.html', context={'form': form})
    
    def post(self, request):
        profile_update_form  = ProfileUpdateForm(instance=request.user, data=request.POST)
        
        if profile_update_form.is_valid():
            profile_update_form.save()
            return redirect('food:index')
        
        return render(request, 'users/profile.html', context={'form': profile_update_form})
    
    
class ProfileView(View):
    def get(self, request):
        
        return render(request, 'users/profile_new.html')

users/templates/users/login.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Kirish{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center mb-4">Kirish</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-block mt-4">Kirish</button>
                </form>
                <p class="mt-3 text-center">Ro'yxatdan o'tmaganmisiz? <a href="{% url 'users:register' %}">Ro'yxatdan o'ting</a></p>
            </div>
        </div>
    </div>


<div class="container mt-5">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/profile.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Profil yangilash{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h1 class="text-center mb-4">Profilni yangilash</h1>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-block mt-4">Saqlash</button>
                    <button class="btn btn-secondary btn-block mt-4"><a style="color: white; text-decoration: none;" href="{% url 'users:password_change' %}">Parolingizni yangilamoqchimisiz?</a></button>
                </form>
            </div>
        </div>
    </div>


<div class="container mt-5">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/profile_new.html
{% extends 'base.html' %}

{% block title %}
    Profile Page
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center mb-4">Профиль</h1>
            <div class="card p-4">
                <div class="text-center">
                    <img src="{{ user.profile_image.url }}" height="100" width="100" style="border-radius: 50%" />
                    <h4 class="mt-3">{{ user.username }}</h4>
                    <p class="text-muted">{{ user.email }}</p>
                    <a href="{% url 'users:profile' %}" class="btn btn-dark">Редактировать профиль</a>
                </div>
                <div class="mt-4 text-center">
                    <div class="social-icons">
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-facebook-f"></i></a>
                        <a href="#"><i class="fa fa-instagram"></i></a>
                        <a href="#"><i class="fa fa-linkedin"></i></a>
                    </div>
                    <div class="mt-3">
                        <p>Присоединился: {{ user.date_joined|date:"d M Y" }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Registratsiya{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="text-center mb-4">Registratsiya</h1>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form|crispy }}
    
                    <button class="btn btn-primary btn-block mt-4" type="submit">Ro'yxatdan o'tish</button>
                </form>
                <p class="mt-3 text-center">Hisobingiz bormi? <a href="{% url 'users:login' %}">Kirish</a></p>
            </div>
        </div>
    </div>


<div class="container mt-5">
    {% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/reset_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <h1 class="text-center mb-4">Parolni tiklash</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-block mt-4">Parolni tiklash</button>
        </form>
        <p class="mt-3 text-center"><a href="{% url 'users:login' %}">Kirish</a> | <a href="{% url 'users:register' %}">Ro'yxatdan o'tish</a></p>
    </div>
</div>
{% endblock %}