config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from . import views
urlpatterns = [
    path('', include('food.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('home/', views.HomeView.as_view(), name='home'),
    
    
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from . import views
from .views import PlacesListView, PlaceDetailView, AddCommentView, UpdateCommentView, DeleteCommentView
app_name = 'food'
urlpatterns = [
    path('', PlacesListView.as_view(), name='index'),
    path('category/<int:id>/', views.category, name='category'),
    path('detail/<int:id>/', PlaceDetailView.as_view(), name='detail'),
    path('<int:id>/comment', AddCommentView.as_view(), name='add_comment'),
    path('comment_update/', UpdateCommentView.as_view(), name='update_comment'),
    path('comment_delete/<int:id>/', DeleteCommentView.as_view(), name='delete_comment'),
]

users/urls.py
from django.urls import path
from . import views
from .views import LoginView, LogoutView, RegisterView, CustomPasswordChangeView
from django.contrib.auth import views as auth_views
app_name = 'users'


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileUpdateView.as_view(), name='profile'),
    path('profile_new/', views.ProfileView.as_view(), name='profile_new'),
    path('password_change/', CustomPasswordChangeView.as_view(), name='password_change'),
    
    path('api/login/', LoginView.as_view(), name='api-login'),
    path('api/logout/', LogoutView.as_view(), name='api-logout'),
    
]

templates/details/about.html
{% load static %}
<section class="section bg-default text-md-start section-md-inset">
    <div class="container">
      <div class="row row-30 align-items-center justify-content-center justify-content-xl-between">
        <div class="col-sm-6 col-md-5 col-lg-6 wow fadeInLeft"><img src="{% static 'food/images/about-576x537.jpg' %}" alt="" width="576" height="537">
        </div>
        <div class="col-md-7 col-lg-6 col-xl-5">
          <h4 class="title-style-1 wow fadeInRight">Ikki og'iz so'z Ilovamiz haqida</h4>
          <h2 class="wow fadeInRight" data-wow-delay=".1s">O'zimiz haqimizda </h2>
          <p class="offset-top-md-20 wow fadeInRight" data-wow-delay=".2s">Bu ilovamizda siz har qanday eng ommabop Ovqatlanish joylarini ko'rishingiz mumkin. Va har bir joyning o'z menyusidan ovqatlar buyurtma berishingiz mumkin</p>
          <div class="group-xl group-middle d-md-flex justify-content-md-between wow fadeInRight" data-wow-delay=".3s">
            <div>
              <div class="group-xl group-middle"><a class="button button-sm button-icon-3 button-primary button-zakaria" href="about-us.html"><span class="mdi mdi-arrow-right"></span></a>
                <div class="team-navy">
                  <div class="team-navy-name"><a href="#">Diyorbek Baxromov</a></div>
                  <div class="team-navy-status">CEO, Founder</div>
                </div>
              </div>
            </div><img src="{% static 'food/images/signature-1-160x55.png' %}" alt="" width="160" height="55">
          </div>
        </div>
      </div>
    </div>
  </section>

templates/details/header.html
{% load static %}
<header class="section page-header">
    <!-- RD Navbar-->
    <div class="rd-navbar-wrap">
      <nav class="rd-navbar rd-navbar-classic" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="100px" data-xl-stick-up-offset="100px" data-xxl-stick-up-offset="100px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
        <div class="rd-navbar-main-outer">
          <div class="rd-navbar-main">
            <!-- RD Navbar Panel-->
            <div class="rd-navbar-panel">
              <!-- RD Navbar Toggle-->
              <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
              <!-- RD Navbar Brand-->
              <div class="rd-navbar-brand"><a class="brand" href="index.html"><img class="brand-logo-dark" src="{% static 'food/images/logo-default-249x52.png' %}" alt="" width="249" height="52"><img class="brand-logo-light" src="images/logo-inverse-249x52.png" alt="" width="249" height="52"></a>
              </div>
            </div>
            <div class="rd-navbar-nav-wrap">
              <!-- RD Navbar Nav-->
              <ul class="rd-navbar-nav">
                <li class="rd-nav-item active"><a class="rd-nav-link" href="{% url 'food:index' %}">Asosiy</a>
                </li>
                
                
                
                
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'home' %}">Izohlar</a>
                  <!-- RD Navbar Dropdown-->
                  
                </li>
                {% if user.is_authenticated %}
                <li class="rd-nav-item"><a class="rd-nav-link" href="#">{{user.username}}</a>
                  <ul class="rd-menu rd-navbar-dropdown">
                    <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="{% url 'users:profile' %}">Profil</a></li>
                    <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="{% url 'users:logout' %}">Chiqish</a></li>


                  </ul>
                </li>

                {% else %}
                
                <li class="rd-nav-item"><a class="rd-nav-link" href="{% url 'users:login' %}">Kirish</a>
                  <ul class="rd-menu rd-navbar-dropdown">
                    <li class="rd-dropdown-item"><a class="rd-dropdown-link" href="{% url 'users:register' %}">Registratsiya</a></li>
                  </ul>
                </li>
                {% endif %}
              </ul>
            </div>
            <div class="rd-navbar-main-element">
              <!-- RD Navbar Search-->
              <div class="rd-navbar-search rd-navbar-search-2">
                <button class="rd-navbar-search-toggle rd-navbar-fixed-element-3" data-rd-navbar-toggle=".rd-navbar-search"><span></span></button>
                <form class="rd-search" action="" data-search-live="rd-search-results-live" method="GET">
                  <div class="form-wrap">
                    <label class="form-label" for="rd-navbar-search-form-input">Search...</label>
                    <input class="rd-navbar-search-form-input form-input" id="rd-navbar-search-form-input" type="text" name="q" value="{{ q }}" >
                    <div class="rd-search-results-live" id="rd-search-results-live"></div>
                    <button class="rd-search-form-submit fl-bigmug-line-search74" type="submit"></button>
                  </div>
                </form>
              </div>
              <!-- RD Navbar Basket-->
              <div class="rd-navbar-basket-wrap">
                <button class="rd-navbar-basket fl-bigmug-line-shopping202" data-rd-navbar-toggle=".cart-inline"><span>2</span></button>
                <div class="cart-inline">
                  <div class="cart-inline-header">
                    <h5 class="cart-inline-title">In cart:<span> 2</span> Products</h5>
                    <h6 class="cart-inline-title">Total price:<span> $43</span></h6>
                  </div>
                  <div class="cart-inline-body">
                    <div class="cart-inline-item">
                      <div class="unit unit-spacing-sm align-items-center">
                        <div class="unit-left"><a class="cart-inline-figure" href="single-product.html"><img src="images/product-mini-6-100x90.png" alt="" width="100" height="90"></a></div>
                        <div class="unit-body">
                          <h6 class="cart-inline-name"><a href="single-product.html">Oranges</a></h6>
                          <div>
                            <div class="group-xs group-middle">
                              <div class="table-cart-stepper">
                                <input class="form-input" type="number" data-zeros="true" value="1" min="1" max="1000">
                              </div>
                              <h6 class="cart-inline-title">$20.00</h6>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="cart-inline-item">
                      <div class="unit unit-spacing-sm align-items-center">
                        <div class="unit-left"><a class="cart-inline-figure" href="single-product.html"><img src="images/product-mini-7-100x90.png" alt="" width="100" height="90"></a></div>
                        <div class="unit-body">
                          <h6 class="cart-inline-name"><a href="single-product.html">Bananas</a></h6>
                          <div>
                            <div class="group-xs group-middle">
                              <div class="table-cart-stepper">
                                <input class="form-input" type="number" data-zeros="true" value="1" min="1" max="1000">
                              </div>
                              <h6 class="cart-inline-title">$23.00</h6>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="cart-inline-footer">
                    <div class="group-sm"><a class="button button-default-outline-2 button-zakaria" href="cart-page.html">Go to cart</a><a class="button button-primary button-zakaria" href="checkout.html">Checkout</a></div>
                  </div>
                </div>
              </div><a class="rd-navbar-basket rd-navbar-basket-mobile fl-bigmug-line-shopping202 rd-navbar-fixed-element-2" href="cart-page.html"><span>2</span></a>
              <button class="rd-navbar-project-hamburger rd-navbar-project-hamburger-open rd-navbar-fixed-element-1" type="button" data-multitoggle=".rd-navbar-main" data-multitoggle-blur=".rd-navbar-wrap" data-multitoggle-isolate="data-multitoggle-isolate"><span class="project-hamburger"><span class="project-hamburger-line"></span><span class="project-hamburger-line"></span><span class="project-hamburger-line"></span><span class="project-hamburger-line"></span></span></button>
            </div>
            <div class="rd-navbar-project">
              <div class="rd-navbar-project-header">
                <button class="rd-navbar-project-hamburger rd-navbar-project-hamburger-close" type="button" data-multitoggle=".rd-navbar-main" data-multitoggle-blur=".rd-navbar-wrap" data-multitoggle-isolate=""><span class="project-close"><span></span><span></span></span></button>
                <h5 class="rd-navbar-project-title">Our Contacts</h5>
              </div>
              <div class="rd-navbar-project-content">
                <div>
                  <div>
                    <!-- Owl Carousel-->
                    <div class="owl-carousel" data-items="1" data-owl="{&quot;dots&quot;:true,&quot;autoplayTimeout&quot;:3500}"><img src="images/about-5-350x269.jpg" alt="" width="350" height="269"><img src="images/about-6-350x269.jpg" alt="" width="350" height="269"><img src="images/about-7-350x269.jpg" alt="" width="350" height="269">
                    </div>
                    <ul class="contacts-modern">
                      <li><a href="#">523 Sylvan Ave, 5th Floor<br>Mountain View, CA 94041 USA</a></li>
                      <li><a href="tel:#">+1 (844) 123 456 78</a></li>
                    </ul>
                  </div>
                  <div>
                    <ul class="list-inline list-social list-inline-xl">
                      <li><a class="icon mdi mdi-facebook" href="#"></a></li>
                      <li><a class="icon mdi mdi-twitter" href="#"></a></li>
                      <li><a class="icon mdi mdi-instagram" href="#"></a></li>
                      <li><a class="icon mdi mdi-google-plus" href="#"></a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
  </header>

templates/details/places.html
{% load static %}
<section class="section section-xxl bg-default">
    <div class="container">
      <h4 class="title-style-1 wow fadeInLeft">Eng mashxurlari</h4>
      <h2 class="wow fadeScale">Categoriyalar</h2>
      <div class="isotope-wrap">
        <div class="isotope-filters">
          <div class="isotope-filters-list-wrap">
            <ul class="isotope-filters-list">

              {% for cat in categories %}

              <li><a href="{% url 'food:category' cat.id %}" >{{cat.name}}</a></li>
              
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="row row-30 row-lg-50 isotope">
        
          {% for place in places %}
          <div class="col-sm-6 col-md-4 col-lg-3 isotope-item">
            <!-- Product-->
            <article class="product wow fadeInRight">
              <div class="product-body">
                <div class="product-figure"><img src="{{place.place_image.url}}" alt="" width="220" height="160">
                </div>
                <h5 class="product-title"><a href="{% url 'food:detail' place.id %}">{{place.name}}</a></h5>
                <div class="product-price-wrap">
                  
                  <div class="product-price">{{ place.description|truncatewords:10 }} </div>
                </div>
            
             
            </article>
          </div>
          {% endfor %}
          

   
          <div class="col-1"></div>
        </div>
      </div>
    </div>
  </section>